os:
  - linux

env:
  - LFTP_SUPPORT=0

language: sh

install:
  - sudo mkdir -p /var/ftp/pub
  - sudo chmod a+rwx /var/ftp/pub
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://security.appspot.com/downloads/vsftpd-3.0.3.tar.gz
      tar xzf vsftpd-3.0.3.tar.gz
      cd vsftpd-3.0.3
      make
      mkdir -p /tmp/vsftpd/empty
      mkdir /tmp/ftp
      ./vsftpd ../tests/vsftpd.conf &
      cd ..
      if [ "$LFTP_SUPPORT" -eq 1 ]; then sudo apt-get install -y lftp; fi
    fi
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      echo "chroot GUEST /var/ftp" | sudo tee -a /etc/ftpd.conf
      echo "modify guest MKD" | sudo tee -a /etc/ftpd.conf
      echo "modify guest RMD" | sudo tee -a /etc/ftpd.conf
      sudo -s launchctl load -w /System/Library/LaunchDaemons/ftp.plist
      if [ "$LFTP_SUPPORT" -eq 1 ]; then brew install lftp; fi
    fi

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - export GIT_FTP_ROOT=ftp://localhost:2121/pub/
  - export GIT_FTP_USER=ftp
  - export GIT_FTP_PASSWD=ftp
  - export TEST_CASES=test_inits

script:
  - curl -v -T INSTALL.md "$GIT_FTP_ROOT"
  - curl -v "$GIT_FTP_ROOT"
  - tests/git-ftp-test.sh

after_failure:
  - cat /tmp/ftp.log
  - cat /tmp/vsftpd-xfer.log
  - ls -la /tmp/ftp/*
  - ls -la /var/ftp/pub/*
