os:
  - linux
#  - osx

env:
  - LFTP_SUPPORT=0
#  - LFTP_SUPPORT=1

language: sh

install:
  - mkdir -p /tmp/ftp/pub
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       wget https://security.appspot.com/downloads/vsftpd-3.0.3.tar.gz
       tar xzf vsftpd-3.0.3.tar.gz
       cd vsftpd-3.0.3
       make
       mkdir -p /tmp/vsftpd/empty
       mkdir /tmp/ftp
       ./vsftpd ../tests/vsftpd.conf &
       cd ..
      #./tests/vsftpd-3.0.3.debian7 tests/vsftpd.conf &
      if [ "$LFTP_SUPPORT" -eq 1 ]; then sudo apt-get install -y lftp; fi
    fi
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ./tests/vsftpd-3.0.3.el_capitan tests/vsftpd.conf &
      if [ "$LFTP_SUPPORT" -eq 1 ]; then brew install lftp; fi
    fi

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - export GIT_FTP_HOST=localhost
  - export GIT_FTP_PORT=:2121
  - export GIT_FTP_ROOT=pub
  - export GIT_FTP_USER=ftp
  - export GIT_FTP_PASSWD=ftp
  - export TEST_CASES="test_inits test_init_fails"

script:
  - tests/git-ftp-test.sh
  - curl ftp://localhost:2121/
  - curl -vvv -u wrong_user:wrong_pw ftp://localhost:2121/

after_failure:
  - cat /tmp/ftp.log
  - ls -la /tmp/ftp/pub
  - ls -la /tmp/ftp/pub/*
